services:
  - type: web
    name: netflix-injector-api
    plan: free
    runtime: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: INJECTOR_SUPABASE_URL
        sync: false
      - key: INJECTOR_SUPABASE_KEY
        sync: false
      - key: AUDIT_SUPABASE_URL
        sync: false
      - key: AUDIT_SUPABASE_KEY
        sync: false
